/**
 * The SINGLE source of truth for every OTLP attribute key the TS SDK emits (H3).
 *
 * Every wire key is a module constant here — the standard OpenTelemetry GenAI
 * `gen_ai.*` keys plus the valuemaxx `ai_margin.*` extensions for the token
 * classes, ids, provenance, and flags the standard semconv does not model.
 *
 * This file is the TypeScript half of a cross-language wire contract. The
 * authoritative key set is generated by the Python side into
 * `tests/wire_contract/semconv_keys.json`; the `semconv-parity` test asserts
 * that {@link ALL_KEYS} is byte-identical to that fixture. The two SDKs share
 * one key set so a span emitted by either language decodes on the same ingest.
 */

// --- standard OpenTelemetry GenAI keys (gen_ai.*) ----------------------------

/** The provider/system (e.g. `anthropic`, `openai`). */
export const GEN_AI_SYSTEM = "gen_ai.system";

/** The model id requested. */
export const GEN_AI_REQUEST_MODEL = "gen_ai.request.model";

/** Total input tokens (the uncached + cached input slices live in extensions). */
export const GEN_AI_USAGE_INPUT_TOKENS = "gen_ai.usage.input_tokens";

/** Total output tokens (terminal value for streaming). */
export const GEN_AI_USAGE_OUTPUT_TOKENS = "gen_ai.usage.output_tokens";

// --- valuemaxx extensions (ai_margin.*) --------------------------------------

/** Cache-read input tokens (priced at the discounted cache-read rate). */
export const AI_MARGIN_CACHE_READ = "ai_margin.usage.cache_read_tokens";

/** 5-minute cache-write input tokens (distinct price from the 1h class). */
export const AI_MARGIN_CACHE_WRITE_5M = "ai_margin.usage.cache_write_5m_tokens";

/** 1-hour cache-write input tokens (distinct price from the 5m class). */
export const AI_MARGIN_CACHE_WRITE_1H = "ai_margin.usage.cache_write_1h_tokens";

/** Reasoning tokens — derived (thinking-block count), embedded within output. */
export const AI_MARGIN_REASONING = "ai_margin.usage.reasoning_tokens";

/** The agent run id this attempt belongs to. */
export const AI_MARGIN_RUN_ID = "ai_margin.run_id";

/** The per-HTTP-attempt id (part of the (run_id, attempt_id) dedup key). */
export const AI_MARGIN_ATTEMPT_ID = "ai_margin.attempt_id";

/** The tenant scope (required; ingest also takes it as a mandatory param). */
export const AI_MARGIN_TENANT_ID = "ai_margin.tenant_id";

/**
 * Which agent produced this call — the dimension a cost rollup groups by to answer
 * "what does THIS agent cost me". Without it every span rolls up under `unknown`,
 * which is the least useful possible grouping for a multi-agent app.
 */
export const AI_MARGIN_AGENT_NAME = "ai_margin.agent_name";

/**
 * Prefix for a run's durable business ids: `ai_margin.entity.alt_id = "alt_123"`.
 *
 * A PREFIX rather than a fixed field because a host names its own units — `alt_id`,
 * `ticket_id`, `loan_application_id`. Cost can then roll up per business entity across
 * however many runs touched it.
 */
export const AI_MARGIN_ENTITY_PREFIX = "ai_margin.entity.";

/** The cost-provenance honesty axis value (measured / provider_reconciled / ...). */
export const AI_MARGIN_PROVENANCE = "ai_margin.provenance";

/** Whether this is per_attempt or the degraded per_call fallback. */
export const AI_MARGIN_CAPTURE_GRANULARITY = "ai_margin.capture_granularity";

/** An authoritative inline cost (e.g. gateway usage.cost); used as-is when present. */
export const AI_MARGIN_COST_USD = "ai_margin.cost_usd";

/** Whether the attempt was a streaming response. */
export const AI_MARGIN_LATENCY_MS = "ai_margin.latency_ms";
/** Wall time for one attempt, to the last byte of a stream (not to headers). */

export const AI_MARGIN_EXPERIMENT = "ai_margin.experiment";
/** Which comparison this call is an arm of. Captured before any engine reads it. */

export const AI_MARGIN_VARIANT = "ai_margin.variant";
/** Which arm of that comparison. */

export const AI_MARGIN_APP = "ai_margin.app";
/** Which of the tenant's apps/surfaces made the call. */

export const AI_MARGIN_CALL_SITE_ID = "ai_margin.call_site_id";
export const AI_MARGIN_SYSTEM_HASH = "ai_margin.config.system_hash";
export const AI_MARGIN_TOOLS_HASH = "ai_margin.config.tools_hash";
export const AI_MARGIN_PARAMS_HASH = "ai_margin.config.params_hash";
export const AI_MARGIN_CONFIG_IDENTITY = "ai_margin.config.identity";
export const AI_MARGIN_CONFIG_IDENTITY_WEAK = "ai_margin.config.identity_weak";
export const AI_MARGIN_HTTP_STATUS = "ai_margin.http_status";

export const AI_MARGIN_IS_STREAMING = "ai_margin.is_streaming";

/** Whether usage was only partially recovered (cancelled / missing include_usage). */
export const AI_MARGIN_PARTIAL_RECOVERED = "ai_margin.partial_recovered";

/**
 * The authoritative set of every OTLP key the capture path uses.
 *
 * Kept as a sorted, readonly tuple so {@link ALL_KEYS} is a stable, ordered
 * value the parity test can compare directly against the JSON fixture's
 * `{"keys": sorted(...)}` array.
 */
export const ALL_KEYS: readonly string[] = Object.freeze(
  [
    GEN_AI_SYSTEM,
    GEN_AI_REQUEST_MODEL,
    GEN_AI_USAGE_INPUT_TOKENS,
    GEN_AI_USAGE_OUTPUT_TOKENS,
    AI_MARGIN_CACHE_READ,
    AI_MARGIN_CACHE_WRITE_5M,
    AI_MARGIN_CACHE_WRITE_1H,
    AI_MARGIN_REASONING,
    AI_MARGIN_RUN_ID,
    AI_MARGIN_ATTEMPT_ID,
    AI_MARGIN_TENANT_ID,
    AI_MARGIN_PROVENANCE,
    AI_MARGIN_CAPTURE_GRANULARITY,
    AI_MARGIN_COST_USD,
    AI_MARGIN_LATENCY_MS,
    AI_MARGIN_EXPERIMENT,
    AI_MARGIN_VARIANT,
    AI_MARGIN_APP,
    AI_MARGIN_CALL_SITE_ID,
    AI_MARGIN_SYSTEM_HASH,
    AI_MARGIN_TOOLS_HASH,
    AI_MARGIN_PARAMS_HASH,
    AI_MARGIN_CONFIG_IDENTITY,
    AI_MARGIN_CONFIG_IDENTITY_WEAK,
    AI_MARGIN_HTTP_STATUS,
    AI_MARGIN_IS_STREAMING,
    AI_MARGIN_PARTIAL_RECOVERED,
  ].sort(),
);
